name: workcake
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.51+2051

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  intl: ^0.17.0 
  get_it: 7.2.0
  http: ^0.13.1
  html: ^0.15.0
  dio: ^4.0.0
  fluro: ^2.0.3
  shimmer: ^2.0.0
  logger: ^1.0.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.12

  google_fonts: ^2.0.0
  path_provider: ^2.0.1 
  # path_provider_macos: ^2.0.0
  # pull_to_refresh: ^1.6.5
  flutter_local_notifications: ^9.0.0
  cached_network_image: ^3.0.0
  extended_image: ^6.0.2+1
  photo_manager: ^2.0.4
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  multi_image_picker: ^4.8.00
  # flutter_image_compress: ^1.0.0
  # flutter_web_auth: ^0.3.0
  dotted_border: ^2.0.0-nullsafety.0
  # image_picker: ^0.7.4
  image_picker: ^0.8.4+4
  lottie: ^1.0.1
  # flutter_skeleton: ^0.1.0+1
  # flutter_mentions: ^2.0.0-nullsafety
  device_info: ^2.0.0
  encrypt: ^5.0.0
  pointycastle: ^3.0.1
  asn1lib: ^1.0.0
  image_downloader: ^0.31.0
  flutter_app_badger: ^1.3.0
  move_to_background: ^1.0.2
  flutter_linkify:
    git:
      url: https://github.com/letungcntt/flutter_linkify
  
  # markdown: ^4.0.0
  # pretty_qr_code: ^1.0.1
  qr_code_scanner:
    git: https://github.com/dunm165913/qr_code_scanner
  image: ^3.0.2
  popover: ^0.2.6+2
  simple_tooltip:

  location: 
    git: https://github.com/dunm165913/location
  undo: ^1.4.0
  stacked_services: 0.9.1
  timeline_tile: ^2.0.0
  flutter_portal: ^0.4.0-nullsafety.0
  flutter_markdown:
  file_selector_platform_interface: ^2.0.0
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.3
  heic_to_jpg: ^0.2.0

  #firebase
  firebase_messaging: ^14.1.1
  firebase_core: ^2.3.0
  scrollable_positioned_list: 0.2.0-nullsafety.0
  rect_getter:
  otp_text_field: ^1.1.1

  flutter_webrtc: 0.9.0
  sdp_transform: ^0.3.0
  wechat_assets_picker: 8.2.0
  wechat_camera_picker: ^3.7.0
  isar: ^0.4.0
  isar_flutter_libs: ^0.4.0 # contains the binaries
  # isar_connect: ^0.2.0 # if you want to use the Isar Inspector

  objectbox: 1.4.1
  objectbox_flutter_libs: 1.4.1

  chewie: ^1.2.1
  video_player: ^2.1.5
  flutter_cache_manager: ^3.3.0
  sliding_up_panel:
  phoenix_wings: ^1.0.2
  sticky_headers: ^0.2.0
  flutter_svg: ^0.22.0
  flutter_keyboard_visibility: ^5.0.3
  phosphor_flutter: ^1.4.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.8
  # workmanager: ^0.4.1
  flutter_otp_text_field: ^1.0.0
  flutter_highlighter: ^0.1.1
  pin_code_fields: ^7.3.0
  vs_scrollbar: ^0.2.0
  collection: ^1.15.0
  image_cropper: ^1.5.0
  video_thumbnail: ^0.4.6
  video_compress: ^3.1.0
  dart_emoji: 
  # connectycube_flutter_call_kit: ^2.0.2
  flutter_callkit_incoming:
    git: https://github.com/dunm165913/flutter_callkit_incoming
  callkeep:
    git: https://github.com/hieplee2997/callkeep.git
  uuid: 3.0.5
  googleapis: ^7.0.0
  google_sign_in: ^5.2.4
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  flutter_vibrate: ^1.3.0
  local_auth: ^2.0.0
  ffmpeg_kit_flutter: ^4.5.1
  native_video_view: ^1.0.5
  gallery_saver: ^2.3.2
  just_audio: ^0.9.21
  record: ^4.1.1
  share_plus: ^4.0.4
  flutter_share: ^2.0.0
  keyboard_actions: ^4.0.0
  flutter_slidable: ^1.3.0
  connectivity_plus: 3.0.3
  network_info_plus: ^3.0.1
  permission_handler: ^10.0.2
  sentry_flutter: ^6.6.3
  crypto: ^3.0.2
  in_app_update: ^3.0.0
  package_info_plus: ^1.4.2
  file_picker: ^4.6.1
  date_picker_timeline: ^1.2.3
  syncfusion_flutter_calendar: ^20.2.50
  flutter_quill:
    git:
      url: https://github.com/letungcntt/flutter-quill
  tuple: ^2.0.0
  fuzzy: ^0.4.0-nullsafety.0
  audioplayers:
  photo_view: ^0.14.0
  expandable: ^5.0.1
  scroll_snap_list: ^0.9.1

dev_dependencies:
  hive_generator: ^1.0.1
  # isar_generator: ^2.2.1
  objectbox_generator: 1.4.1
  build_runner: 
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/images/icons/
    - assets/images/emoji_used/
    - assets/images/emoji_smile/
    - assets/images/emoji_animal/
    - assets/images/emoji_food/
    - assets/images/logo_app/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/helveticaneuebold.ttf
        - asset: assets/fonts/helveticaneuebolditalic.ttf
        - asset: assets/fonts/helveticaneuecondensedblack.ttf
        - asset: assets/fonts/helveticaneuecondensedbold.ttf
        - asset: assets/fonts/helveticaneueitalic.ttf
        - asset: assets/fonts/helveticaneuelight.ttf
        - asset: assets/fonts/helveticaneuelightitalic.ttf
        - asset: assets/fonts/helveticaneuemedium.ttf
        - asset: assets/fonts/helveticaneueultralight.ttf
        - asset: assets/fonts/helveticaneueultralightitalic.ttf
        
  #     - assets/lang/vi.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
# dependency_overrides:
#   intl: ^0.17.0-nullsafety.2

dependency_overrides:
  platform: ^3.1.0
  camera_android: 0.10.4
